name: CI Pipeline

on:
    push:
        branches:
            - main  # Trigger the workflow on pushes to the main branch
    pull_request:
        branches:
            - main  # Trigger the workflow on pull requests to the main branch

jobs:
    test:
        runs-on: ubuntu-latest  # Use the latest Ubuntu environment

        steps:
        - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code

        - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.9'  # Use the latest Python 3.x version

        - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        - name: Run the script
        run: |
        echo "Testing the script with input 3"
        echo "3" | python calculator.py

